spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.3.38/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
redis:
  host: localhost
  port: 6379
env:
  dev
  
#server:
#  port: 8081
